control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
match_block_trailing_comma = true
trailing_comma = "Never"
wrap_comments = true
comment_width = 160
max_width = 160
use_small_heuristics = "Max"
single_line_if_else_max_width = 0